TEST_DURATION_SECONDS = 30 * 60  # 30 minutes
NUM_TEST_QUESTIONS = 30

QUESTION_FILE_PATH = "assets/grile.json"
PDF_DIR_PATH = "assets/pdf"
IMAGES_DIR_PATH = "assets/images"

WINDOW_WIDTH_RATIO = 0.8
WINDOW_HEIGHT_RATIO = 0.8
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600

STYLE_CORRECT = "MyCorrect"
STYLE_WRONG = "MyWrong"
